const data = [
  {
    id: 1,
    brandName: "ACER",
    category: "Laptops",
    productName: "Acer Nitro 5 AN517-54-79L1 Gaming Laptop",
    price: 1119,
    image: require("./Assests/Laptops/AcerNitro5AN517.jpg"),
    sale: false,
    quantity: 1,
    total: 0,
  },
  {
    id: 2,
    brandName: "MSI",
    category: "Laptops",
    productName: "MSI GF63 Thin Laptop",
    price: 959,
    image: require("./Assests/Laptops/msi-_0035_GF63-Thin-10SCXR-4.jpg"),
    sale: false,
    quantity: 1,
    total: 0,
  },
  {
    id: 3,
    brandName: "ASUS",
    category: "Laptops",
    productName: "ASUS ROG Zephyrus S Ultra Slim",
    price: 2219,
    image: require("./Assests/Laptops/Asus-ROG-Zephyrus-S-GU502.jpg"),
    sale: false,
    quantity: 1,
    total: 0,
  },
  {
    id: 4,
    brandName: "DELL",
    category: "Laptops",
    productName: "ALIENWARE AREA-51M",
    price: 4523,
    sale: false,
    image: require("./Assests/Laptops/dell-alienware-area-51m-gaming-laptop.jpg"),
    quantity: 1,
    total: 0,
  },
  {
    id: 5,
    brandName: "ACER",
    category: "Laptops",
    productName: "Acer Swift 7 ",
    sale: true,
    price: 1058,
    image: require("./Assests/Laptops/AcerSwift7SF714-52T__1_.jpg"),
    quantity: 1,
    total: 0,
  },
  {
    id: 6,
    brandName: "ACER",
    category: "Laptops",
    productName: "Acer Nitro 5 ",
    price: 789.0,
    sale: false,
    image: require("./Assests/Laptops/LD0005846339_1.jpg"),
    quantity: 1,
    total: 0,
  },
  {
    id: 7,
    brandName: "HP",
    category: "Laptops",
    productName: "HP ZBook 15u G5 ",
    sale: false,
    price: 1499.0,
    image: require("./Assests/Laptops/41ami1qQ9pL._AC_SY350_.jpg"),
    quantity: 1,
    total: 0,
  },
  {
    id: 8,
    brandName: "Logitech",
    category: "Accessories",
    sale: true,
    productName: "Logitech G430 USB Gaming Headset",
    price: 60.0,
    image: require("./Assests/Accessories/Logitech-G430-500x500-1.jpg"),
    quantity: 1,
    total: 0,
  },
  {
    id: 9,
    brandName: "Gamdias",
    sale: false,
    category: "Accessories",
    productName: "Gamdias HEBE M1 Premium Virtual Surround Sound",
    price: 62.0,
    image: require("./Assests/Accessories/Gamdias-HEBE-M1-Ultimate-7.1-1-500x500-1.jpg"),
    quantity: 1,
    total: 0,
  },

  {
    id: 10,
    brandName: "Logitech",
    sale: false,
    category: "Accessories",
    productName:
      "Logitech G402 Hyperion Fury Ultra Fast FPS Gaming Mouse 4000 DPI, 1ms Report Time",
    price: 80.0,
    image: require("./Assests/Accessories/logitech-g402-hyperion-fury-gaming-mouse-price-nepal_1.jpg"),
    quantity: 1,
    total: 0,
  },

  {
    id: 11,
    brandName: "Logitech",
    category: "Accessories",
    productName:
      "Logitech BCC950 All-in-One Webcam and Speakerphone - 1080p video, 1' Screen, In-built Mic",
    price: 400.0,
    image: require("./Assests/Accessories/logitech-conference-cam-bcc950-price-nepal.jpg"),
    sale: false,
    quantity: 1,
    total: 0,
  },

  {
    id: 12,
    brandName: "Logitech",
    category: "Accessories",
    productName:
      "Logitech C310 HD WebCam - 720p Video with Noise Reducing Mic, Lighting Correction",
    price: 45.0,
    image: require("./Assests/Accessories/logitech-c310-hd-webcam-price-nepal-laptops-desktops.jpg"),
    sale: true,
    quantity: 1,
    total: 0,
  },

  {
    id: 13,
    brandName: "Logitech",
    category: "Accessories",
    productName: "LOGITECH MK235 WIRELESS KEYBOARD AND MOUSE COMBO SET",
    price: 32.0,
    image: require("./Assests/Accessories/mk235_1.jpg"),
    sale: false,
    quantity: 1,
    total: 0,
  },

  {
    id: 14,
    brandName: "Rapoo",
    category: "Accessories",
    productName:
      "Rapoo V500 Pro Mechanical Gaming RGB Keyboard - Individual Backlit Keys, Spill Resistant",
    price: 55.0,
    image: require("./Assests/Accessories/rapoo-v500-pro-budget-gaming-mechanical-keyboard-price-nepal-rgb-lighting.jpg"),
    sale: false,
    quantity: 1,
    total: 0,
  },
  {
    id: 15,
    brandName: "DELL",
    category: "Laptops",
    productName:
      "Dell Inspiron 3505 Ryzen5-3450U/8GB RAM/256GB SSD/16.5″ Full HD-Touch/Windows 10 Home",
    price: 700.0,
    image: require("./Assests/Laptops/3505-1-300x300.jpg"),
    sale: false,
    quantity: 1,
    total: 0,
  },
];

export default data;
